title: Celine Apollon 
logo: "C:\Users\Celine\Documents\GitHub\CAPOLLON PORTFOLIO\Celine-Apollon-Portfolio\images\prof_pic" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  others-centered urbanist, data scientists, creator, and thinker 
  <br><br>
  <a href="https://www.linkedin.com/in/celine-apollon3/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

